model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251227122614'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251227122614
  result_save_dir: ./output/resmlp/20251227122614
  model_save_path: ./output/resmlp/20251227122614/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 21.01418685913086
    MSE: 0.0006350853363983333
    RMSE: 25.200899515658826
    R2: 0.9999944567680359
  eval_time: '20251227200822'
