model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 8
  learning_rate: 0.001
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251226205145'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251226205145
  result_save_dir: ./output/resmlp/20251226205145
  model_save_path: ./output/resmlp/20251226205145/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 20.498579025268555
    MSE: 0.0006533869891427457
    RMSE: 25.56143558454309
    R2: 0.9999942779541016
  eval_time: '20251226232750'
