model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 0.0001
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251227203335'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251227203335
  result_save_dir: ./output/resmlp/20251227203335
  model_save_path: ./output/resmlp/20251227203335/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.97072982788086
    MSE: 0.000601269886828959
    RMSE: 24.520805183128857
    R2: 0.9999947547912598
  eval_time: '20251227205405'
