model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 0.005
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251227212918'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251227212918
  result_save_dir: ./output/resmlp/20251227212918
  model_save_path: ./output/resmlp/20251227212918/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 20.474437713623047
    MSE: 0.0006243360112421215
    RMSE: 24.986716695919082
    R2: 0.9999945163726807
  eval_time: '20251228162851'
