model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251226232956'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251226232956
  result_save_dir: ./output/resmlp/20251226232956
  model_save_path: ./output/resmlp/20251226232956/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 20.02904510498047
    MSE: 0.0005816646153107285
    RMSE: 24.117724090608725
    R2: 0.9999949336051941
  eval_time: '20251227091416'
