model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 5.0e-06
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251228202938'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251228202938
  result_save_dir: ./output/resmlp/20251228202938
  model_save_path: ./output/resmlp/20251228202938/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 20.042301177978516
    MSE: 0.0006075250566937029
    RMSE: 24.648023383097133
    R2: 0.999994695186615
  eval_time: '20251228215914'
