model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 64
  learning_rate: 0.005
  epochs: 10000
  patience: 2000
  loss: Huber
  optimizer: Rprop
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251223221734'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251223221734
  result_save_dir: ./output/resmlp/20251223221734
  model_save_path: ./output/resmlp/20251223221734/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.266096115112305
    MSE: 0.000558339583221823
    RMSE: 23.629210380836323
    R2: 0.9999951124191284
  eval_time: '20251223223432'
