model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 5.0e-05
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251228233909'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251228233909
  result_save_dir: ./output/resmlp/20251228233909
  model_save_path: ./output/resmlp/20251228233909/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.819122314453125
    MSE: 0.0005908494931645691
    RMSE: 24.307395853208323
    R2: 0.9999948143959045
  eval_time: '20251229144622'
