model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 2.0e-05
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251230173230'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251230173230
  result_save_dir: ./output/resmlp/20251230173230
  model_save_path: ./output/resmlp/20251230173230/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 20.356765747070312
    MSE: 0.0006244091200642288
    RMSE: 24.98817960685069
    R2: 0.9999945163726807
  eval_time: '20251230224008'

# 模型结构为非残差，直接寻找映射关系