model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 64
  learning_rate: 0.035
  epochs: 100000
  patience: 20000
  loss: Huber
  optimizer: Rprop
  scheduler:
    type: CosineAnnealingLR
    T_max: 100000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251221235456'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251221235456
  result_save_dir: ./output/resmlp/20251221235456
  model_save_path: ./output/resmlp/20251221235456/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 21.126102447509766
    MSE: 0.0006626513786613941
    RMSE: 25.74201582357905
    R2: 0.9999942183494568
  eval_time: '20251222011022'
