model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 1.5e-05
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251229230627'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251229230627
  result_save_dir: ./output/resmlp/20251229230627
  model_save_path: ./output/resmlp/20251229230627/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.238542556762695
    MSE: 0.0005690688267350197
    RMSE: 23.855163523543904
    R2: 0.9999950528144836
  eval_time: '20251230100912'
