model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 2.5e-05
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251229213024'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251229213024
  result_save_dir: ./output/resmlp/20251229213024
  model_save_path: ./output/resmlp/20251229213024/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.14241600036621
    MSE: 0.000562633911613375
    RMSE: 23.71990538795159
    R2: 0.9999950528144836
  eval_time: '20251229230453'
