model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 16
  learning_rate: 0.001
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251227093823'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251227093823
  result_save_dir: ./output/resmlp/20251227093823
  model_save_path: ./output/resmlp/20251227093823/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 22.89510154724121
    MSE: 0.0007168134907260537
    RMSE: 26.77337279324467
    R2: 0.9999937415122986
  eval_time: '20251227102641'
