model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 1.0e-06
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251228164839'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251228164839
  result_save_dir: ./output/resmlp/20251228164839
  model_save_path: ./output/resmlp/20251228164839/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 21.175878524780273
    MSE: 0.0007037744508124888
    RMSE: 26.528747629929477
    R2: 0.9999938607215881
  eval_time: '20251228200800'
