model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 3.0e-05
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251229154847'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251229154847
  result_save_dir: ./output/resmlp/20251229154847
  model_save_path: ./output/resmlp/20251229154847/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.45551109313965
    MSE: 0.0005828159628435969
    RMSE: 24.141581614376406
    R2: 0.9999948740005493
  eval_time: '20251229212910'
