model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 1.0e-05
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251227211646'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251227211646
  result_save_dir: ./output/resmlp/20251227211646
  model_save_path: ./output/resmlp/20251227211646/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.17920684814453
    MSE: 0.000557656167075038
    RMSE: 23.614744696376416
    R2: 0.9999951124191284
  eval_time: '20251228164431'
