model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 8
  learning_rate: 0.005
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251224154902'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251224154902
  result_save_dir: ./output/resmlp/20251224154902
  model_save_path: ./output/resmlp/20251224154902/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.168554306030273
    MSE: 0.0005560202989727259
    RMSE: 23.58008267527334
    R2: 0.9999951124191284
  eval_time: '20251224160059'
