model:
  type: resmlp
  arch:
  - 128
  - 256
  - 256
  - 128
  - 64
training:
  batch_size: 32
  learning_rate: 7.5e-06
  epochs: 10000
  patience: 2000
  loss: MSE
  optimizer: Adam
  scheduler:
    type: CosineAnnealingLR
    T_max: 10000
data:
  train_csv: ./input/20251216/train.csv
  eval_csv: ./input/20251216/eval.csv
runtime:
  run_time: '20251228220002'
  device: cpu
paths:
  model_save_dir: ./output/resmlp/20251228220002
  result_save_dir: ./output/resmlp/20251228220002
  model_save_path: ./output/resmlp/20251228220002/resmlp_128-256-256-128-64.pth
evaluation:
  metrics:
    MAE: 19.703643798828125
    MSE: 0.0005880814860574901
    RMSE: 24.250391461943252
    R2: 0.9999948740005493
  eval_time: '20251228233717'
